// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBg-SwYrmgn0B86hFBvBhEhkwA1a4a6jY',
    appId: '1:437363827129:web:0ec035dc89109fb8175668',
    messagingSenderId: '437363827129',
    projectId: 'sales-task-manager',
    authDomain: 'sales-task-manager.firebaseapp.com',
    storageBucket: 'sales-task-manager.appspot.com',
    measurementId: 'G-3Z5VH8H67B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtMUJwbyosoKRviK3azf5QtLQWrYZ_BE0',
    appId: '1:437363827129:android:7fe89b9c06055150175668',
    messagingSenderId: '437363827129',
    projectId: 'sales-task-manager',
    storageBucket: 'sales-task-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM38CKYFPF6-yXJRYOT5AUaStV4ciqKyc',
    appId: '1:437363827129:ios:56f19c709cffc178175668',
    messagingSenderId: '437363827129',
    projectId: 'sales-task-manager',
    storageBucket: 'sales-task-manager.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM38CKYFPF6-yXJRYOT5AUaStV4ciqKyc',
    appId: '1:437363827129:ios:faeeef4947e0fb9f175668',
    messagingSenderId: '437363827129',
    projectId: 'sales-task-manager',
    storageBucket: 'sales-task-manager.appspot.com',
    iosBundleId: 'com.example.taskManager.RunnerTests',
  );
}
